/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Server;

import java.awt.Font;
import static java.awt.image.ImageObserver.HEIGHT;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author nicho
 */
public class PasswordGUI extends javax.swing.JDialog {
    
    private Settings setting= new Settings();
    private EnterPasswordGUI enterPass= new EnterPasswordGUI(null, true);
    private String pass= null;

    /**
     * Creates new form PasswordGUI
     */
    public PasswordGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        refresh();
    }
    
    private void refresh(){
        boolean passOn= setting.getBoolValue("sbsPassActiveServer");
        if(passOn){
            labelPassOnOff.setIcon(new ImageIcon(getClass().getResource(labelDeviceOn)));
        }
        else{
            labelPassOnOff.setIcon(new ImageIcon(getClass().getResource(labelDeviceOff)));
        }
    }
    
    private boolean getInfo(){
        pass= fieldPass.getText();
        if(pass.length()>0){
            if(pass.length()<4){
                JLabel msgLabel= new JLabel();
                msgLabel.setFont(new Font ("Microsoft tai le", Font.BOLD, 16));
                msgLabel.setText("Password must contains at least 4 characters");
                JOptionPane.showMessageDialog(rootPane, msgLabel, null, HEIGHT, new ImageIcon(getClass().getResource(errorIcon)));
                return false;
            }
            if(pass.length()>10){
                JLabel msgLabel= new JLabel();
                msgLabel.setFont(new Font ("Microsoft tai le", Font.BOLD, 16));
                msgLabel.setText("Password cannot contains more than 10 characters");
                JOptionPane.showMessageDialog(rootPane, msgLabel, null, HEIGHT, new ImageIcon(getClass().getResource(errorIcon)));
                return false;
            }
            return true;
        }
        JLabel msgLabel= new JLabel();
        msgLabel.setFont(new Font ("Microsoft tai le", Font.BOLD, 16));
        msgLabel.setText("Enter a new password before Save");
        JOptionPane.showMessageDialog(rootPane, msgLabel, null, HEIGHT, new ImageIcon(getClass().getResource(errorIcon)));
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelPass = new javax.swing.JLabel();
        labelOnOff = new javax.swing.JLabel();
        labelPassOnOff = new javax.swing.JLabel();
        labelNewPass = new javax.swing.JLabel();
        fieldPass = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        labelPass.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        labelPass.setForeground(new java.awt.Color(0, 0, 255));
        labelPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Server/Icons/password-icon-40x40.png"))); // NOI18N
        labelPass.setText("Password");

        labelOnOff.setFont(new java.awt.Font("Microsoft Tai Le", 1, 16)); // NOI18N
        labelOnOff.setText("On/Off");

        labelPassOnOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Server/Icons/switch-on-icon-70x30.png"))); // NOI18N
        labelPassOnOff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelPassOnOffMouseClicked(evt);
            }
        });

        labelNewPass.setFont(new java.awt.Font("Microsoft Tai Le", 1, 16)); // NOI18N
        labelNewPass.setText("New Password");

        btnSave.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Server/Icons/save-floppy-icon-30x30.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnClose.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Server/Icons/close-icon-30x30.png"))); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelPass)
                                .addGap(56, 56, 56)
                                .addComponent(labelOnOff)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelPassOnOff))
                            .addComponent(labelNewPass))
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addComponent(fieldPass)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnClose)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPassOnOff)
                    .addComponent(labelPass)
                    .addComponent(labelOnOff))
                .addGap(18, 18, 18)
                .addComponent(labelNewPass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if(getInfo()){
            if(setting.getBoolValue("sbsPassActiveServer")){
                enterPass.setVisible(true);
                if(setting.getBoolValue("sbsPassCorrectServer")){
                    setting.SaveSetting("string", "sbsPassServer", pass);
                    setting.SaveSetting("bool", "sbsPassActiveServer", "true");
                    JLabel msgLabel= new JLabel();
                    msgLabel.setFont(new Font ("Microsoft tai le", Font.BOLD, 16));
                    msgLabel.setText("Password changed");
                    JOptionPane.showMessageDialog(rootPane, msgLabel, null, HEIGHT, new ImageIcon(getClass().getResource(infoIcon)));
                }
                this.dispose();
                return;
            }
            JLabel msgLabel= new JLabel();
            msgLabel.setFont(new Font ("Microsoft tai le", Font.BOLD, 16));
            msgLabel.setText("Password changed");
            JOptionPane.showMessageDialog(rootPane, msgLabel, null, HEIGHT, new ImageIcon(getClass().getResource(infoIcon)));
            
            setting.SaveSetting("string", "sbsPassServer", pass);
            setting.SaveSetting("bool", "sbsPassActiveServer", "true");
            
            this.dispose();
        }
        refresh();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void labelPassOnOffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelPassOnOffMouseClicked
        boolean passOn= setting.getBoolValue("sbsPassActiveServer");
        String getPass= setting.getStingValue("sbsPassServer");
        if(passOn){
            enterPass.setVisible(true);
            if(setting.getBoolValue("sbsPassCorrectServer")){
                setting.SaveSetting("bool", "sbsPassActiveServer", "false");
                setting.SaveSetting("string", "sbsPassServer", "");
            }
        }
        else{
            if(getPass!=null && getPass.length()>2){
                setting.SaveSetting("bool", "sbsPassActiveServer", "true");
            }
            else{
                JLabel msgLabel= new JLabel();
                msgLabel.setFont(new Font ("Microsoft tai le", Font.BOLD, 16));
                msgLabel.setText("Enter a new password");
                JOptionPane.showMessageDialog(rootPane, msgLabel, null, HEIGHT, new ImageIcon(getClass().getResource(errorIcon)));
            }
        }
        refresh();
    }//GEN-LAST:event_labelPassOnOffMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PasswordGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PasswordGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PasswordGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PasswordGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PasswordGUI dialog = new PasswordGUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    //***************ICONS DATABASE START***************
        String errorIcon= "/Server/Icons/error-logo-50x50.png";
        String labelDeviceOn= "/Server/Icons/switch-on-icon-70x30.png";
        String labelDeviceOff= "/Server/Icons/switch-off-icon-70x30.png";
        String infoIcon= "/Server/Icons/info-icon-50x50.png";
    //***************ICONS DATABASE END*****************

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSave;
    private javax.swing.JTextField fieldPass;
    private javax.swing.JLabel labelNewPass;
    private javax.swing.JLabel labelOnOff;
    private javax.swing.JLabel labelPass;
    private javax.swing.JLabel labelPassOnOff;
    // End of variables declaration//GEN-END:variables
}
