/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Server;

import java.awt.Font;
import static java.awt.image.ImageObserver.HEIGHT;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author nicho
 */
public class UpdateUserGUI extends javax.swing.JDialog {
    
    private DateTimeFormatter dtf = DateTimeFormatter.ofPattern("MMM-dd-yyyy");
    private String pass= null;
    private String expireDateStr= null;
    private String email= null;
    private String userId= null;
    private CmrFileManager cmrFileMan;

    /**
     * Creates new form UpdateUserGUI
     */
    public UpdateUserGUI(java.awt.Frame parent, boolean modal, String userId) {
        super(parent, modal);
        initComponents();
        this.userId= userId;
        btnUpInfo.setEnabled(false);
        btnUpExpire.setEnabled(false);
        btnUpEmail.setEnabled(false);
        labelDate.setText("");
        labelUserId.setText(userId);
        cmrFileMan= new CmrFileManager();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userInfoLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelUserId = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtFieldEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFieldPass = new javax.swing.JTextField();
        btnUpInfo = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        expireLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelDate = new javax.swing.JLabel();
        btnAddYear = new javax.swing.JButton();
        txtFieldCus = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnUpExpire = new javax.swing.JButton();
        btnClose2 = new javax.swing.JButton();
        btnUpEmail = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        expireLabel1 = new javax.swing.JLabel();
        btnResetCounter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(473, 470));
        setResizable(false);

        userInfoLabel.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        userInfoLabel.setForeground(new java.awt.Color(0, 0, 255));
        userInfoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Server/Icons/admin-icon-40x40.png"))); // NOI18N
        userInfoLabel.setText("User Info");

        jLabel7.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel7.setText("User ID:");

        labelUserId.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        labelUserId.setForeground(new java.awt.Color(0, 0, 255));
        labelUserId.setText("id");

        jLabel6.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel6.setText("Email");

        txtFieldEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFieldEmailMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel4.setText("Password");

        txtFieldPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFieldPassMouseClicked(evt);
            }
        });

        btnUpInfo.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        btnUpInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Server/Icons/update-user-pass-30x30.png"))); // NOI18N
        btnUpInfo.setText("Update User Pass");
        btnUpInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpInfoActionPerformed(evt);
            }
        });

        expireLabel.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        expireLabel.setForeground(new java.awt.Color(0, 0, 255));
        expireLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Server/Icons/calendar-icon-40x40.png"))); // NOI18N
        expireLabel.setText("Expire");

        jLabel5.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel5.setText("Expire Date: ");

        labelDate.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        labelDate.setForeground(new java.awt.Color(0, 0, 255));
        labelDate.setText("DATE");

        btnAddYear.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        btnAddYear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Server/Icons/365-year-icon-30x30.png"))); // NOI18N
        btnAddYear.setText("Add One Year");
        btnAddYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddYearActionPerformed(evt);
            }
        });

        txtFieldCus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFieldCusKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        jLabel3.setText("Custom Date (MMM-dd-yyyy) ");

        btnUpExpire.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        btnUpExpire.setForeground(new java.awt.Color(0, 204, 0));
        btnUpExpire.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Server/Icons/user_update_edit_30x30.png"))); // NOI18N
        btnUpExpire.setText("Update Expire");
        btnUpExpire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpExpireActionPerformed(evt);
            }
        });

        btnClose2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        btnClose2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Server/Icons/close-icon-30x30.png"))); // NOI18N
        btnClose2.setText("Close");
        btnClose2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClose2ActionPerformed(evt);
            }
        });

        btnUpEmail.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        btnUpEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Server/Icons/email-icon-30x30.png"))); // NOI18N
        btnUpEmail.setText("Update User Email");
        btnUpEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpEmailActionPerformed(evt);
            }
        });

        expireLabel1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        expireLabel1.setForeground(new java.awt.Color(0, 0, 255));
        expireLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Server/Icons/pc-computer-icon-45x40.png"))); // NOI18N
        expireLabel1.setText("Mac Counter");

        btnResetCounter.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        btnResetCounter.setForeground(new java.awt.Color(0, 204, 0));
        btnResetCounter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Server/Icons/user_update_edit_30x30.png"))); // NOI18N
        btnResetCounter.setText("Reset Counter");
        btnResetCounter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetCounterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFieldPass, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddYear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtFieldCus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnUpEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUpInfo))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(userInfoLabel)
                                .addGap(35, 35, 35)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelUserId))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(expireLabel)
                                .addGap(55, 55, 55)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelDate))
                            .addComponent(expireLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUpExpire, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnClose2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnResetCounter)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userInfoLabel)
                    .addComponent(jLabel7)
                    .addComponent(labelUserId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFieldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expireLabel)
                    .addComponent(jLabel5)
                    .addComponent(labelDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAddYear)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(3, 3, 3)
                        .addComponent(txtFieldCus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpExpire, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(expireLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnResetCounter, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClose2))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddYearActionPerformed
        expireDateStr= dtf.format(LocalDate.now().plusYears(1));
        txtFieldCus.setText("");
        labelDate.setText(expireDateStr);
        btnUpExpire.setEnabled(true);
    }//GEN-LAST:event_btnAddYearActionPerformed

    private void btnClose2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClose2ActionPerformed
        dispose();
    }//GEN-LAST:event_btnClose2ActionPerformed

    private void txtFieldEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFieldEmailMouseClicked
        btnUpEmail.setEnabled(true);
    }//GEN-LAST:event_txtFieldEmailMouseClicked

    private void txtFieldPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFieldPassMouseClicked
        btnUpInfo.setEnabled(true);
    }//GEN-LAST:event_txtFieldPassMouseClicked

    private void txtFieldCusKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldCusKeyPressed
        btnUpExpire.setEnabled(true);
    }//GEN-LAST:event_txtFieldCusKeyPressed

    private void btnUpExpireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpExpireActionPerformed
        if(expireDateStr!=null){
            cmrFileMan.updateUserExpire(userId, expireDateStr);
            labelDate.setText(expireDateStr);
            JLabel msgLabel= new JLabel();
            msgLabel.setFont(new Font ("Microsoft tai le", Font.BOLD, 16));
            msgLabel.setText("Expire updated");
            JOptionPane.showMessageDialog(rootPane, msgLabel, null, HEIGHT, new ImageIcon(getClass().getResource(infoIcon)));
        }
        else{
            expireDateStr= txtFieldCus.getText();
            if(expireDateStr!=null || expireDateStr.length()>2){
                cmrFileMan.updateUserExpire(userId, expireDateStr);
                labelDate.setText(expireDateStr);
                JLabel msgLabel= new JLabel();
                msgLabel.setFont(new Font ("Microsoft tai le", Font.BOLD, 16));
                msgLabel.setText("Expire updated");
                JOptionPane.showMessageDialog(rootPane, msgLabel, null, HEIGHT, new ImageIcon(getClass().getResource(infoIcon)));
            }
            else{
                JLabel msgLabel= new JLabel();
                msgLabel.setFont(new Font ("Microsoft tai le", Font.BOLD, 16));
                msgLabel.setText("Invalid date");
                JOptionPane.showMessageDialog(rootPane, msgLabel, null, HEIGHT, new ImageIcon(getClass().getResource(errorIcon)));
            }
        }
    }//GEN-LAST:event_btnUpExpireActionPerformed

    private void btnUpEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpEmailActionPerformed
        email= txtFieldEmail.getText();
        if(email.length()>2){
            cmrFileMan.updateUserEmail(userId, email);
            labelDate.setText(expireDateStr);
            JLabel msgLabel= new JLabel();
            msgLabel.setFont(new Font ("Microsoft tai le", Font.BOLD, 16));
            msgLabel.setText("Email updated");
            JOptionPane.showMessageDialog(rootPane, msgLabel, null, HEIGHT, new ImageIcon(getClass().getResource(infoIcon)));
        }
        else{
            JLabel msgLabel= new JLabel();
            msgLabel.setFont(new Font ("Microsoft tai le", Font.BOLD, 16));
            msgLabel.setText("Invalid email");
            JOptionPane.showMessageDialog(rootPane, msgLabel, null, HEIGHT, new ImageIcon(getClass().getResource(errorIcon)));
        }        
    }//GEN-LAST:event_btnUpEmailActionPerformed

    private void btnUpInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpInfoActionPerformed
        pass= txtFieldPass.getText();
        if(pass.length()>2){
            cmrFileMan.updateUserPass(userId, pass);
            labelDate.setText(expireDateStr);
            JLabel msgLabel= new JLabel();
            msgLabel.setFont(new Font ("Microsoft tai le", Font.BOLD, 16));
            msgLabel.setText("Password updated");
            JOptionPane.showMessageDialog(rootPane, msgLabel, null, HEIGHT, new ImageIcon(getClass().getResource(infoIcon)));
        }
        else{
            JLabel msgLabel= new JLabel();
            msgLabel.setFont(new Font ("Microsoft tai le", Font.BOLD, 16));
            msgLabel.setText("Invalid password");
            JOptionPane.showMessageDialog(rootPane, msgLabel, null, HEIGHT, new ImageIcon(getClass().getResource(errorIcon)));
        } 
    }//GEN-LAST:event_btnUpInfoActionPerformed

    private void btnResetCounterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetCounterActionPerformed
        cmrFileMan.resetUserMacCounter(userId);
        JLabel msgLabel= new JLabel();
        msgLabel.setFont(new Font ("Microsoft tai le", Font.BOLD, 16));
        msgLabel.setText("Mac Counter reset");
        JOptionPane.showMessageDialog(rootPane, msgLabel, null, HEIGHT, new ImageIcon(getClass().getResource(infoIcon)));
    }//GEN-LAST:event_btnResetCounterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateUserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateUserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateUserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateUserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UpdateUserGUI dialog = new UpdateUserGUI(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    //***************ICONS DATABASE START***************
        String errorIcon= "/Server/Icons/error-logo-50x50.png";
        String infoIcon= "/Server/Icons/info-icon-50x50.png";
        
        //new ImageIcon(getClass().getResource(ICON))
    //***************ICONS DATABASE END*****************

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddYear;
    private javax.swing.JButton btnClose2;
    private javax.swing.JButton btnResetCounter;
    private javax.swing.JButton btnUpEmail;
    private javax.swing.JButton btnUpExpire;
    private javax.swing.JButton btnUpInfo;
    private javax.swing.JLabel expireLabel;
    private javax.swing.JLabel expireLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel labelDate;
    private javax.swing.JLabel labelUserId;
    private javax.swing.JTextField txtFieldCus;
    private javax.swing.JTextField txtFieldEmail;
    private javax.swing.JTextField txtFieldPass;
    private javax.swing.JLabel userInfoLabel;
    // End of variables declaration//GEN-END:variables
}
