/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SBS;

import java.awt.Font;
import static java.awt.image.ImageObserver.HEIGHT;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author nicho
 */
public class AutopilotGUI extends javax.swing.JDialog {
    
    Settings setting= new Settings();

    /**
     * Creates new form AutopilotGUI
     */
    public AutopilotGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Autopilot Settings");
        setTimesBox();
        resfresh();
    }
    
    private void resfresh(){
        String days= setting.getStingValue("autoPilotDays");
        String time= setting.getStingValue("autoPilotTime");
        if(days!=null && days.length()>2){
            if(days.contains("Mon")) checkMon.setSelected(true);
            if(days.contains("Tue")) checkTue.setSelected(true);
            if(days.contains("Wed")) checkWed.setSelected(true);
            if(days.contains("Thu")) checkThu.setSelected(true);
            if(days.contains("Fri")) checkFri.setSelected(true);
            if(days.contains("Sat")) checkSat.setSelected(true);
            if(days.contains("Sun")) checkSun.setSelected(true);
        }
        labelTimeSet.setText(time);
    }
    
    private boolean getInfo(){
        String tmpDays= "";
        String tmpTime= "";
        if(checkMon.isSelected()) tmpDays+="Mon-";
        if(checkTue.isSelected()) tmpDays+="Tue-";
        if(checkWed.isSelected()) tmpDays+="Wed-";
        if(checkThu.isSelected()) tmpDays+="Thu-";
        if(checkFri.isSelected()) tmpDays+="Fri-";
        if(checkSat.isSelected()) tmpDays+="Sat-";
        if(checkSun.isSelected()) tmpDays+="Sun";
        tmpTime= timeBox.getSelectedItem().toString();
        if(tmpDays.length()<2 || tmpTime.length()<2){
            JLabel msgLabel= new JLabel();
            msgLabel.setFont(new Font ("Microsoft tai le", Font.BOLD, 16));
            msgLabel.setText("Set time and days before save settings");
            JOptionPane.showMessageDialog(rootPane, msgLabel, null, HEIGHT, new ImageIcon(getClass().getResource(errorIcon)));
           return false;
        }
        setting.SaveSetting("String", "autoPilotDays", tmpDays);
        setting.SaveSetting("String", "autoPilotTime", tmpTime);
        return true;
    }
    
    private void setTimesBox(){
        timeBox.removeAllItems();
        timeBox.addItem("");
        for(int i=0; i<24; i++){
            String time;
            time= String.format("%02d", i) + ":00";
            timeBox.addItem(time);
            time= String.format("%02d", i) + ":30";
            timeBox.addItem(time);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        checkMon = new javax.swing.JCheckBox();
        checkTue = new javax.swing.JCheckBox();
        checkWed = new javax.swing.JCheckBox();
        checkThu = new javax.swing.JCheckBox();
        checkFri = new javax.swing.JCheckBox();
        checkSat = new javax.swing.JCheckBox();
        checkSun = new javax.swing.JCheckBox();
        btnEveryday = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        timeBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelTimeSet = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SBS/Icons/calendar-icon-40x40.png"))); // NOI18N
        jLabel1.setText("Days");

        checkMon.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        checkMon.setText("Monday");

        checkTue.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        checkTue.setText("Tuesday");

        checkWed.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        checkWed.setText("Wednesday");

        checkThu.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        checkThu.setText("Thursday");

        checkFri.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        checkFri.setText("Friday");

        checkSat.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        checkSat.setText("Saturday");

        checkSun.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        checkSun.setText("Sunday");

        btnEveryday.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        btnEveryday.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SBS/Icons/calendar-icon-week-30x30.png"))); // NOI18N
        btnEveryday.setText("Everyday");
        btnEveryday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEverydayActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SBS/Icons/clock-icon-40x40.png"))); // NOI18N
        jLabel2.setText("Time");

        jLabel3.setFont(new java.awt.Font("Microsoft Tai Le", 1, 16)); // NOI18N
        jLabel3.setText("Choose time");

        jLabel4.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel4.setText("Time set");

        labelTimeSet.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        labelTimeSet.setText("??:??");

        btnSave.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SBS/Icons/save-floppy-icon-30x30.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnClose.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SBS/Icons/close-icon-30x30.png"))); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEveryday))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnClose)
                        .addGap(18, 18, 18)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(checkMon)
                                        .addGap(18, 18, 18)
                                        .addComponent(checkWed))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(checkTue)
                                        .addGap(18, 18, 18)
                                        .addComponent(checkThu)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkSat)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(checkFri)
                                        .addGap(36, 36, 36)
                                        .addComponent(checkSun))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(labelTimeSet))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(timeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnEveryday))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkMon)
                    .addComponent(checkWed)
                    .addComponent(checkFri)
                    .addComponent(checkSun))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkTue)
                    .addComponent(checkThu)
                    .addComponent(checkSat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(labelTimeSet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        boolean close= getInfo();
        resfresh();
        if(close) this.dispose();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnEverydayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEverydayActionPerformed
        checkMon.setSelected(true);
        checkTue.setSelected(true);
        checkWed.setSelected(true);
        checkThu.setSelected(true);
        checkFri.setSelected(true);
        checkSat.setSelected(true);
        checkSun.setSelected(true);
    }//GEN-LAST:event_btnEverydayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AutopilotGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AutopilotGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AutopilotGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AutopilotGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AutopilotGUI dialog = new AutopilotGUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    
    //***************ICONS DATABASE START***************
        String errorIcon= "/SBS/Icons/error-logo-50x50.png";
    //***************ICONS DATABASE END*****************

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnEveryday;
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox checkFri;
    private javax.swing.JCheckBox checkMon;
    private javax.swing.JCheckBox checkSat;
    private javax.swing.JCheckBox checkSun;
    private javax.swing.JCheckBox checkThu;
    private javax.swing.JCheckBox checkTue;
    private javax.swing.JCheckBox checkWed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel labelTimeSet;
    private javax.swing.JButton saveConSetBtn;
    private javax.swing.JComboBox<String> timeBox;
    // End of variables declaration//GEN-END:variables
}
